// Generated by gencpp from file color_sorting/SetTarget.msg
// DO NOT EDIT!


#ifndef COLOR_SORTING_MESSAGE_SETTARGET_H
#define COLOR_SORTING_MESSAGE_SETTARGET_H

#include <ros/service_traits.h>


#include <color_sorting/SetTargetRequest.h>
#include <color_sorting/SetTargetResponse.h>


namespace color_sorting
{

struct SetTarget
{

typedef SetTargetRequest Request;
typedef SetTargetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget
} // namespace color_sorting


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::color_sorting::SetTarget > {
  static const char* value()
  {
    return "d59dc51bea53a4877185283f71dbf83c";
  }

  static const char* value(const ::color_sorting::SetTarget&) { return value(); }
};

template<>
struct DataType< ::color_sorting::SetTarget > {
  static const char* value()
  {
    return "color_sorting/SetTarget";
  }

  static const char* value(const ::color_sorting::SetTarget&) { return value(); }
};


// service_traits::MD5Sum< ::color_sorting::SetTargetRequest> should match
// service_traits::MD5Sum< ::color_sorting::SetTarget >
template<>
struct MD5Sum< ::color_sorting::SetTargetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::color_sorting::SetTarget >::value();
  }
  static const char* value(const ::color_sorting::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_sorting::SetTargetRequest> should match
// service_traits::DataType< ::color_sorting::SetTarget >
template<>
struct DataType< ::color_sorting::SetTargetRequest>
{
  static const char* value()
  {
    return DataType< ::color_sorting::SetTarget >::value();
  }
  static const char* value(const ::color_sorting::SetTargetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::color_sorting::SetTargetResponse> should match
// service_traits::MD5Sum< ::color_sorting::SetTarget >
template<>
struct MD5Sum< ::color_sorting::SetTargetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::color_sorting::SetTarget >::value();
  }
  static const char* value(const ::color_sorting::SetTargetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::color_sorting::SetTargetResponse> should match
// service_traits::DataType< ::color_sorting::SetTarget >
template<>
struct DataType< ::color_sorting::SetTargetResponse>
{
  static const char* value()
  {
    return DataType< ::color_sorting::SetTarget >::value();
  }
  static const char* value(const ::color_sorting::SetTargetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // COLOR_SORTING_MESSAGE_SETTARGET_H
