// Generated by gencpp from file jetmax_control/FK.msg
// DO NOT EDIT!


#ifndef JETMAX_CONTROL_MESSAGE_FK_H
#define JETMAX_CONTROL_MESSAGE_FK_H

#include <ros/service_traits.h>


#include <jetmax_control/FKRequest.h>
#include <jetmax_control/FKResponse.h>


namespace jetmax_control
{

struct FK
{

typedef FKRequest Request;
typedef FKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FK
} // namespace jetmax_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetmax_control::FK > {
  static const char* value()
  {
    return "dc592708003b91537cff0bcafe06c7d7";
  }

  static const char* value(const ::jetmax_control::FK&) { return value(); }
};

template<>
struct DataType< ::jetmax_control::FK > {
  static const char* value()
  {
    return "jetmax_control/FK";
  }

  static const char* value(const ::jetmax_control::FK&) { return value(); }
};


// service_traits::MD5Sum< ::jetmax_control::FKRequest> should match
// service_traits::MD5Sum< ::jetmax_control::FK >
template<>
struct MD5Sum< ::jetmax_control::FKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetmax_control::FK >::value();
  }
  static const char* value(const ::jetmax_control::FKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetmax_control::FKRequest> should match
// service_traits::DataType< ::jetmax_control::FK >
template<>
struct DataType< ::jetmax_control::FKRequest>
{
  static const char* value()
  {
    return DataType< ::jetmax_control::FK >::value();
  }
  static const char* value(const ::jetmax_control::FKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetmax_control::FKResponse> should match
// service_traits::MD5Sum< ::jetmax_control::FK >
template<>
struct MD5Sum< ::jetmax_control::FKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetmax_control::FK >::value();
  }
  static const char* value(const ::jetmax_control::FKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetmax_control::FKResponse> should match
// service_traits::DataType< ::jetmax_control::FK >
template<>
struct DataType< ::jetmax_control::FKResponse>
{
  static const char* value()
  {
    return DataType< ::jetmax_control::FK >::value();
  }
  static const char* value(const ::jetmax_control::FKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETMAX_CONTROL_MESSAGE_FK_H
