// Generated by gencpp from file jetmax_control/IK.msg
// DO NOT EDIT!


#ifndef JETMAX_CONTROL_MESSAGE_IK_H
#define JETMAX_CONTROL_MESSAGE_IK_H

#include <ros/service_traits.h>


#include <jetmax_control/IKRequest.h>
#include <jetmax_control/IKResponse.h>


namespace jetmax_control
{

struct IK
{

typedef IKRequest Request;
typedef IKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IK
} // namespace jetmax_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetmax_control::IK > {
  static const char* value()
  {
    return "14fb54e9e518f55d418823395ca25d0b";
  }

  static const char* value(const ::jetmax_control::IK&) { return value(); }
};

template<>
struct DataType< ::jetmax_control::IK > {
  static const char* value()
  {
    return "jetmax_control/IK";
  }

  static const char* value(const ::jetmax_control::IK&) { return value(); }
};


// service_traits::MD5Sum< ::jetmax_control::IKRequest> should match
// service_traits::MD5Sum< ::jetmax_control::IK >
template<>
struct MD5Sum< ::jetmax_control::IKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetmax_control::IK >::value();
  }
  static const char* value(const ::jetmax_control::IKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetmax_control::IKRequest> should match
// service_traits::DataType< ::jetmax_control::IK >
template<>
struct DataType< ::jetmax_control::IKRequest>
{
  static const char* value()
  {
    return DataType< ::jetmax_control::IK >::value();
  }
  static const char* value(const ::jetmax_control::IKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetmax_control::IKResponse> should match
// service_traits::MD5Sum< ::jetmax_control::IK >
template<>
struct MD5Sum< ::jetmax_control::IKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetmax_control::IK >::value();
  }
  static const char* value(const ::jetmax_control::IKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetmax_control::IKResponse> should match
// service_traits::DataType< ::jetmax_control::IK >
template<>
struct DataType< ::jetmax_control::IKResponse>
{
  static const char* value()
  {
    return DataType< ::jetmax_control::IK >::value();
  }
  static const char* value(const ::jetmax_control::IKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETMAX_CONTROL_MESSAGE_IK_H
