; Auto-generated. Do not edit!


(cl:in-package opc_ros-msg)


;//! \htmlinclude ActionSetRawGoal.msg.html

(cl:defclass <ActionSetRawGoal> (roslisp-msg-protocol:ros-message)
  ((data
    :reader data
    :initarg :data
    :type cl:string
    :initform "")
   (repeat
    :reader repeat
    :initarg :repeat
    :type cl:integer
    :initform 0))
)

(cl:defclass ActionSetRawGoal (<ActionSetRawGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionSetRawGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionSetRawGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name opc_ros-msg:<ActionSetRawGoal> is deprecated: use opc_ros-msg:ActionSetRawGoal instead.")))

(cl:ensure-generic-function 'data-val :lambda-list '(m))
(cl:defmethod data-val ((m <ActionSetRawGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader opc_ros-msg:data-val is deprecated.  Use opc_ros-msg:data instead.")
  (data m))

(cl:ensure-generic-function 'repeat-val :lambda-list '(m))
(cl:defmethod repeat-val ((m <ActionSetRawGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader opc_ros-msg:repeat-val is deprecated.  Use opc_ros-msg:repeat instead.")
  (repeat m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionSetRawGoal>) ostream)
  "Serializes a message object of type '<ActionSetRawGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'data))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'data))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'repeat)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'repeat)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'repeat)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'repeat)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionSetRawGoal>) istream)
  "Deserializes a message object of type '<ActionSetRawGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'data) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'data) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'repeat)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'repeat)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'repeat)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'repeat)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionSetRawGoal>)))
  "Returns string type for a message object of type '<ActionSetRawGoal>"
  "opc_ros/ActionSetRawGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionSetRawGoal)))
  "Returns string type for a message object of type 'ActionSetRawGoal"
  "opc_ros/ActionSetRawGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionSetRawGoal>)))
  "Returns md5sum for a message object of type '<ActionSetRawGoal>"
  "58ae1817d1d041c9a34f0f909e7566dc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionSetRawGoal)))
  "Returns md5sum for a message object of type 'ActionSetRawGoal"
  "58ae1817d1d041c9a34f0f909e7566dc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionSetRawGoal>)))
  "Returns full string definition for message of type '<ActionSetRawGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string data~%uint32 repeat~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionSetRawGoal)))
  "Returns full string definition for message of type 'ActionSetRawGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string data~%uint32 repeat~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionSetRawGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'data))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionSetRawGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionSetRawGoal
    (cl:cons ':data (data msg))
    (cl:cons ':repeat (repeat msg))
))
