; Auto-generated. Do not edit!


(cl:in-package opc_ros-msg)


;//! \htmlinclude ActionSetRawResult.msg.html

(cl:defclass <ActionSetRawResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ActionSetRawResult (<ActionSetRawResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionSetRawResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionSetRawResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name opc_ros-msg:<ActionSetRawResult> is deprecated: use opc_ros-msg:ActionSetRawResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <ActionSetRawResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader opc_ros-msg:result-val is deprecated.  Use opc_ros-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionSetRawResult>) ostream)
  "Serializes a message object of type '<ActionSetRawResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionSetRawResult>) istream)
  "Deserializes a message object of type '<ActionSetRawResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionSetRawResult>)))
  "Returns string type for a message object of type '<ActionSetRawResult>"
  "opc_ros/ActionSetRawResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionSetRawResult)))
  "Returns string type for a message object of type 'ActionSetRawResult"
  "opc_ros/ActionSetRawResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionSetRawResult>)))
  "Returns md5sum for a message object of type '<ActionSetRawResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionSetRawResult)))
  "Returns md5sum for a message object of type 'ActionSetRawResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionSetRawResult>)))
  "Returns full string definition for message of type '<ActionSetRawResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionSetRawResult)))
  "Returns full string definition for message of type 'ActionSetRawResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionSetRawResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionSetRawResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionSetRawResult
    (cl:cons ':result (result msg))
))
