# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from remote_control/Status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Status(genpy.Message):
  _md5sum = "590d96bbbe0686d00dc0bf91b47e905e"
  _type = "remote_control/Status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 x
int16 y
int16 z
uint16 id1
uint16 id2
uint16 id3
uint16 id4
uint8 pwm1
uint8 motor1
uint8 motor2

"""
  __slots__ = ['x','y','z','id1','id2','id3','id4','pwm1','motor1','motor2']
  _slot_types = ['int16','int16','int16','uint16','uint16','uint16','uint16','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,id1,id2,id3,id4,pwm1,motor1,motor2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0
      if self.y is None:
        self.y = 0
      if self.z is None:
        self.z = 0
      if self.id1 is None:
        self.id1 = 0
      if self.id2 is None:
        self.id2 = 0
      if self.id3 is None:
        self.id3 = 0
      if self.id4 is None:
        self.id4 = 0
      if self.pwm1 is None:
        self.pwm1 = 0
      if self.motor1 is None:
        self.motor1 = 0
      if self.motor2 is None:
        self.motor2 = 0
    else:
      self.x = 0
      self.y = 0
      self.z = 0
      self.id1 = 0
      self.id2 = 0
      self.id3 = 0
      self.id4 = 0
      self.pwm1 = 0
      self.motor1 = 0
      self.motor2 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3h4H3B().pack(_x.x, _x.y, _x.z, _x.id1, _x.id2, _x.id3, _x.id4, _x.pwm1, _x.motor1, _x.motor2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.x, _x.y, _x.z, _x.id1, _x.id2, _x.id3, _x.id4, _x.pwm1, _x.motor1, _x.motor2,) = _get_struct_3h4H3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3h4H3B().pack(_x.x, _x.y, _x.z, _x.id1, _x.id2, _x.id3, _x.id4, _x.pwm1, _x.motor1, _x.motor2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.x, _x.y, _x.z, _x.id1, _x.id2, _x.id3, _x.id4, _x.pwm1, _x.motor1, _x.motor2,) = _get_struct_3h4H3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3h4H3B = None
def _get_struct_3h4H3B():
    global _struct_3h4H3B
    if _struct_3h4H3B is None:
        _struct_3h4H3B = struct.Struct("<3h4H3B")
    return _struct_3h4H3B
