; Auto-generated. Do not edit!


(cl:in-package jetmax_control-msg)


;//! \htmlinclude ActionSetRawFeedback.msg.html

(cl:defclass <ActionSetRawFeedback> (roslisp-msg-protocol:ros-message)
  ((index
    :reader index
    :initarg :index
    :type cl:integer
    :initform 0)
   (count
    :reader count
    :initarg :count
    :type cl:integer
    :initform 0))
)

(cl:defclass ActionSetRawFeedback (<ActionSetRawFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ActionSetRawFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ActionSetRawFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name jetmax_control-msg:<ActionSetRawFeedback> is deprecated: use jetmax_control-msg:ActionSetRawFeedback instead.")))

(cl:ensure-generic-function 'index-val :lambda-list '(m))
(cl:defmethod index-val ((m <ActionSetRawFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jetmax_control-msg:index-val is deprecated.  Use jetmax_control-msg:index instead.")
  (index m))

(cl:ensure-generic-function 'count-val :lambda-list '(m))
(cl:defmethod count-val ((m <ActionSetRawFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader jetmax_control-msg:count-val is deprecated.  Use jetmax_control-msg:count instead.")
  (count m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ActionSetRawFeedback>) ostream)
  "Serializes a message object of type '<ActionSetRawFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'index)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'count)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'count)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ActionSetRawFeedback>) istream)
  "Deserializes a message object of type '<ActionSetRawFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'index)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'count)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'count)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ActionSetRawFeedback>)))
  "Returns string type for a message object of type '<ActionSetRawFeedback>"
  "jetmax_control/ActionSetRawFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ActionSetRawFeedback)))
  "Returns string type for a message object of type 'ActionSetRawFeedback"
  "jetmax_control/ActionSetRawFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ActionSetRawFeedback>)))
  "Returns md5sum for a message object of type '<ActionSetRawFeedback>"
  "9bd522b74b786e5c761ef1c23a598fdf")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ActionSetRawFeedback)))
  "Returns md5sum for a message object of type 'ActionSetRawFeedback"
  "9bd522b74b786e5c761ef1c23a598fdf")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ActionSetRawFeedback>)))
  "Returns full string definition for message of type '<ActionSetRawFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 index~%uint32 count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ActionSetRawFeedback)))
  "Returns full string definition for message of type 'ActionSetRawFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint32 index~%uint32 count~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ActionSetRawFeedback>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ActionSetRawFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ActionSetRawFeedback
    (cl:cons ':index (index msg))
    (cl:cons ':count (count msg))
))
