(cl:defpackage jetmax_control-srv
  (:use )
  (:export
   "ACTIONSETFILEOP"
   "<ACTIONSETFILEOP-REQUEST>"
   "ACTIONSETFILEOP-REQUEST"
   "<ACTIONSETFILEOP-RESPONSE>"
   "ACTIONSETFILEOP-RESPONSE"
   "ACTIONSETLIST"
   "<ACTIONSETLIST-REQUEST>"
   "ACTIONSETLIST-REQUEST"
   "<ACTIONSETLIST-RESPONSE>"
   "ACTIONSETLIST-RESPONSE"
  ))

