// Generated by gencpp from file jetmax_control/ActionSetFileOp.msg
// DO NOT EDIT!


#ifndef JETMAX_CONTROL_MESSAGE_ACTIONSETFILEOP_H
#define JETMAX_CONTROL_MESSAGE_ACTIONSETFILEOP_H

#include <ros/service_traits.h>


#include <jetmax_control/ActionSetFileOpRequest.h>
#include <jetmax_control/ActionSetFileOpResponse.h>


namespace jetmax_control
{

struct ActionSetFileOp
{

typedef ActionSetFileOpRequest Request;
typedef ActionSetFileOpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionSetFileOp
} // namespace jetmax_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetmax_control::ActionSetFileOp > {
  static const char* value()
  {
    return "272e984a50155b54f97a32954cf22782";
  }

  static const char* value(const ::jetmax_control::ActionSetFileOp&) { return value(); }
};

template<>
struct DataType< ::jetmax_control::ActionSetFileOp > {
  static const char* value()
  {
    return "jetmax_control/ActionSetFileOp";
  }

  static const char* value(const ::jetmax_control::ActionSetFileOp&) { return value(); }
};


// service_traits::MD5Sum< ::jetmax_control::ActionSetFileOpRequest> should match
// service_traits::MD5Sum< ::jetmax_control::ActionSetFileOp >
template<>
struct MD5Sum< ::jetmax_control::ActionSetFileOpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetmax_control::ActionSetFileOp >::value();
  }
  static const char* value(const ::jetmax_control::ActionSetFileOpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetmax_control::ActionSetFileOpRequest> should match
// service_traits::DataType< ::jetmax_control::ActionSetFileOp >
template<>
struct DataType< ::jetmax_control::ActionSetFileOpRequest>
{
  static const char* value()
  {
    return DataType< ::jetmax_control::ActionSetFileOp >::value();
  }
  static const char* value(const ::jetmax_control::ActionSetFileOpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetmax_control::ActionSetFileOpResponse> should match
// service_traits::MD5Sum< ::jetmax_control::ActionSetFileOp >
template<>
struct MD5Sum< ::jetmax_control::ActionSetFileOpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetmax_control::ActionSetFileOp >::value();
  }
  static const char* value(const ::jetmax_control::ActionSetFileOpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetmax_control::ActionSetFileOpResponse> should match
// service_traits::DataType< ::jetmax_control::ActionSetFileOp >
template<>
struct DataType< ::jetmax_control::ActionSetFileOpResponse>
{
  static const char* value()
  {
    return DataType< ::jetmax_control::ActionSetFileOp >::value();
  }
  static const char* value(const ::jetmax_control::ActionSetFileOpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETMAX_CONTROL_MESSAGE_ACTIONSETFILEOP_H
