// Generated by gencpp from file jetmax_control/ActionSetList.msg
// DO NOT EDIT!


#ifndef JETMAX_CONTROL_MESSAGE_ACTIONSETLIST_H
#define JETMAX_CONTROL_MESSAGE_ACTIONSETLIST_H

#include <ros/service_traits.h>


#include <jetmax_control/ActionSetListRequest.h>
#include <jetmax_control/ActionSetListResponse.h>


namespace jetmax_control
{

struct ActionSetList
{

typedef ActionSetListRequest Request;
typedef ActionSetListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionSetList
} // namespace jetmax_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jetmax_control::ActionSetList > {
  static const char* value()
  {
    return "eef2f65442e5649b9b3489933fa21e88";
  }

  static const char* value(const ::jetmax_control::ActionSetList&) { return value(); }
};

template<>
struct DataType< ::jetmax_control::ActionSetList > {
  static const char* value()
  {
    return "jetmax_control/ActionSetList";
  }

  static const char* value(const ::jetmax_control::ActionSetList&) { return value(); }
};


// service_traits::MD5Sum< ::jetmax_control::ActionSetListRequest> should match
// service_traits::MD5Sum< ::jetmax_control::ActionSetList >
template<>
struct MD5Sum< ::jetmax_control::ActionSetListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jetmax_control::ActionSetList >::value();
  }
  static const char* value(const ::jetmax_control::ActionSetListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetmax_control::ActionSetListRequest> should match
// service_traits::DataType< ::jetmax_control::ActionSetList >
template<>
struct DataType< ::jetmax_control::ActionSetListRequest>
{
  static const char* value()
  {
    return DataType< ::jetmax_control::ActionSetList >::value();
  }
  static const char* value(const ::jetmax_control::ActionSetListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jetmax_control::ActionSetListResponse> should match
// service_traits::MD5Sum< ::jetmax_control::ActionSetList >
template<>
struct MD5Sum< ::jetmax_control::ActionSetListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jetmax_control::ActionSetList >::value();
  }
  static const char* value(const ::jetmax_control::ActionSetListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jetmax_control::ActionSetListResponse> should match
// service_traits::DataType< ::jetmax_control::ActionSetList >
template<>
struct DataType< ::jetmax_control::ActionSetListResponse>
{
  static const char* value()
  {
    return DataType< ::jetmax_control::ActionSetList >::value();
  }
  static const char* value(const ::jetmax_control::ActionSetListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JETMAX_CONTROL_MESSAGE_ACTIONSETLIST_H
