// Generated by gencpp from file remote_control/ChangePosition.msg
// DO NOT EDIT!


#ifndef REMOTE_CONTROL_MESSAGE_CHANGEPOSITION_H
#define REMOTE_CONTROL_MESSAGE_CHANGEPOSITION_H

#include <ros/service_traits.h>


#include <remote_control/ChangePositionRequest.h>
#include <remote_control/ChangePositionResponse.h>


namespace remote_control
{

struct ChangePosition
{

typedef ChangePositionRequest Request;
typedef ChangePositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangePosition
} // namespace remote_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::remote_control::ChangePosition > {
  static const char* value()
  {
    return "792555415d8fe5c4e60a69456efc5174";
  }

  static const char* value(const ::remote_control::ChangePosition&) { return value(); }
};

template<>
struct DataType< ::remote_control::ChangePosition > {
  static const char* value()
  {
    return "remote_control/ChangePosition";
  }

  static const char* value(const ::remote_control::ChangePosition&) { return value(); }
};


// service_traits::MD5Sum< ::remote_control::ChangePositionRequest> should match
// service_traits::MD5Sum< ::remote_control::ChangePosition >
template<>
struct MD5Sum< ::remote_control::ChangePositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::ChangePosition >::value();
  }
  static const char* value(const ::remote_control::ChangePositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::ChangePositionRequest> should match
// service_traits::DataType< ::remote_control::ChangePosition >
template<>
struct DataType< ::remote_control::ChangePositionRequest>
{
  static const char* value()
  {
    return DataType< ::remote_control::ChangePosition >::value();
  }
  static const char* value(const ::remote_control::ChangePositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::remote_control::ChangePositionResponse> should match
// service_traits::MD5Sum< ::remote_control::ChangePosition >
template<>
struct MD5Sum< ::remote_control::ChangePositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::ChangePosition >::value();
  }
  static const char* value(const ::remote_control::ChangePositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::ChangePositionResponse> should match
// service_traits::DataType< ::remote_control::ChangePosition >
template<>
struct DataType< ::remote_control::ChangePositionResponse>
{
  static const char* value()
  {
    return DataType< ::remote_control::ChangePosition >::value();
  }
  static const char* value(const ::remote_control::ChangePositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REMOTE_CONTROL_MESSAGE_CHANGEPOSITION_H
