// Generated by gencpp from file remote_control/SetChuck.msg
// DO NOT EDIT!


#ifndef REMOTE_CONTROL_MESSAGE_SETCHUCK_H
#define REMOTE_CONTROL_MESSAGE_SETCHUCK_H

#include <ros/service_traits.h>


#include <remote_control/SetChuckRequest.h>
#include <remote_control/SetChuckResponse.h>


namespace remote_control
{

struct SetChuck
{

typedef SetChuckRequest Request;
typedef SetChuckResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetChuck
} // namespace remote_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::remote_control::SetChuck > {
  static const char* value()
  {
    return "be1a696a40f3aa3626e65e8ab32b15fa";
  }

  static const char* value(const ::remote_control::SetChuck&) { return value(); }
};

template<>
struct DataType< ::remote_control::SetChuck > {
  static const char* value()
  {
    return "remote_control/SetChuck";
  }

  static const char* value(const ::remote_control::SetChuck&) { return value(); }
};


// service_traits::MD5Sum< ::remote_control::SetChuckRequest> should match
// service_traits::MD5Sum< ::remote_control::SetChuck >
template<>
struct MD5Sum< ::remote_control::SetChuckRequest>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::SetChuck >::value();
  }
  static const char* value(const ::remote_control::SetChuckRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::SetChuckRequest> should match
// service_traits::DataType< ::remote_control::SetChuck >
template<>
struct DataType< ::remote_control::SetChuckRequest>
{
  static const char* value()
  {
    return DataType< ::remote_control::SetChuck >::value();
  }
  static const char* value(const ::remote_control::SetChuckRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::remote_control::SetChuckResponse> should match
// service_traits::MD5Sum< ::remote_control::SetChuck >
template<>
struct MD5Sum< ::remote_control::SetChuckResponse>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::SetChuck >::value();
  }
  static const char* value(const ::remote_control::SetChuckResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::SetChuckResponse> should match
// service_traits::DataType< ::remote_control::SetChuck >
template<>
struct DataType< ::remote_control::SetChuckResponse>
{
  static const char* value()
  {
    return DataType< ::remote_control::SetChuck >::value();
  }
  static const char* value(const ::remote_control::SetChuckResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REMOTE_CONTROL_MESSAGE_SETCHUCK_H
