// Generated by gencpp from file remote_control/SetChuckRequest.msg
// DO NOT EDIT!


#ifndef REMOTE_CONTROL_MESSAGE_SETCHUCKREQUEST_H
#define REMOTE_CONTROL_MESSAGE_SETCHUCKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace remote_control
{
template <class ContainerAllocator>
struct SetChuckRequest_
{
  typedef SetChuckRequest_<ContainerAllocator> Type;

  SetChuckRequest_()
    : absorb(false)  {
    }
  SetChuckRequest_(const ContainerAllocator& _alloc)
    : absorb(false)  {
  (void)_alloc;
    }



   typedef uint8_t _absorb_type;
  _absorb_type absorb;





  typedef boost::shared_ptr< ::remote_control::SetChuckRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::remote_control::SetChuckRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetChuckRequest_

typedef ::remote_control::SetChuckRequest_<std::allocator<void> > SetChuckRequest;

typedef boost::shared_ptr< ::remote_control::SetChuckRequest > SetChuckRequestPtr;
typedef boost::shared_ptr< ::remote_control::SetChuckRequest const> SetChuckRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::remote_control::SetChuckRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::remote_control::SetChuckRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::remote_control::SetChuckRequest_<ContainerAllocator1> & lhs, const ::remote_control::SetChuckRequest_<ContainerAllocator2> & rhs)
{
  return lhs.absorb == rhs.absorb;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::remote_control::SetChuckRequest_<ContainerAllocator1> & lhs, const ::remote_control::SetChuckRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace remote_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::remote_control::SetChuckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::remote_control::SetChuckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote_control::SetChuckRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::remote_control::SetChuckRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote_control::SetChuckRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::remote_control::SetChuckRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::remote_control::SetChuckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1762e658520cf4cba4e60a27f0cac0e";
  }

  static const char* value(const ::remote_control::SetChuckRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1762e658520cf4cULL;
  static const uint64_t static_value2 = 0xba4e60a27f0cac0eULL;
};

template<class ContainerAllocator>
struct DataType< ::remote_control::SetChuckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "remote_control/SetChuckRequest";
  }

  static const char* value(const ::remote_control::SetChuckRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::remote_control::SetChuckRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool absorb\n"
;
  }

  static const char* value(const ::remote_control::SetChuckRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::remote_control::SetChuckRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.absorb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetChuckRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::remote_control::SetChuckRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::remote_control::SetChuckRequest_<ContainerAllocator>& v)
  {
    s << indent << "absorb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.absorb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REMOTE_CONTROL_MESSAGE_SETCHUCKREQUEST_H
