// Generated by gencpp from file remote_control/SetPWMServo.msg
// DO NOT EDIT!


#ifndef REMOTE_CONTROL_MESSAGE_SETPWMSERVO_H
#define REMOTE_CONTROL_MESSAGE_SETPWMSERVO_H

#include <ros/service_traits.h>


#include <remote_control/SetPWMServoRequest.h>
#include <remote_control/SetPWMServoResponse.h>


namespace remote_control
{

struct SetPWMServo
{

typedef SetPWMServoRequest Request;
typedef SetPWMServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPWMServo
} // namespace remote_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::remote_control::SetPWMServo > {
  static const char* value()
  {
    return "6e1eb645b22b8412b0f366c1854f41ef";
  }

  static const char* value(const ::remote_control::SetPWMServo&) { return value(); }
};

template<>
struct DataType< ::remote_control::SetPWMServo > {
  static const char* value()
  {
    return "remote_control/SetPWMServo";
  }

  static const char* value(const ::remote_control::SetPWMServo&) { return value(); }
};


// service_traits::MD5Sum< ::remote_control::SetPWMServoRequest> should match
// service_traits::MD5Sum< ::remote_control::SetPWMServo >
template<>
struct MD5Sum< ::remote_control::SetPWMServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::SetPWMServo >::value();
  }
  static const char* value(const ::remote_control::SetPWMServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::SetPWMServoRequest> should match
// service_traits::DataType< ::remote_control::SetPWMServo >
template<>
struct DataType< ::remote_control::SetPWMServoRequest>
{
  static const char* value()
  {
    return DataType< ::remote_control::SetPWMServo >::value();
  }
  static const char* value(const ::remote_control::SetPWMServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::remote_control::SetPWMServoResponse> should match
// service_traits::MD5Sum< ::remote_control::SetPWMServo >
template<>
struct MD5Sum< ::remote_control::SetPWMServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::SetPWMServo >::value();
  }
  static const char* value(const ::remote_control::SetPWMServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::SetPWMServoResponse> should match
// service_traits::DataType< ::remote_control::SetPWMServo >
template<>
struct DataType< ::remote_control::SetPWMServoResponse>
{
  static const char* value()
  {
    return DataType< ::remote_control::SetPWMServo >::value();
  }
  static const char* value(const ::remote_control::SetPWMServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REMOTE_CONTROL_MESSAGE_SETPWMSERVO_H
