// Generated by gencpp from file remote_control/SetPosition.msg
// DO NOT EDIT!


#ifndef REMOTE_CONTROL_MESSAGE_SETPOSITION_H
#define REMOTE_CONTROL_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <remote_control/SetPositionRequest.h>
#include <remote_control/SetPositionResponse.h>


namespace remote_control
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace remote_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::remote_control::SetPosition > {
  static const char* value()
  {
    return "b0eee1376ff6f9ce415abb3534488423";
  }

  static const char* value(const ::remote_control::SetPosition&) { return value(); }
};

template<>
struct DataType< ::remote_control::SetPosition > {
  static const char* value()
  {
    return "remote_control/SetPosition";
  }

  static const char* value(const ::remote_control::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::remote_control::SetPositionRequest> should match
// service_traits::MD5Sum< ::remote_control::SetPosition >
template<>
struct MD5Sum< ::remote_control::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::SetPosition >::value();
  }
  static const char* value(const ::remote_control::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::SetPositionRequest> should match
// service_traits::DataType< ::remote_control::SetPosition >
template<>
struct DataType< ::remote_control::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::remote_control::SetPosition >::value();
  }
  static const char* value(const ::remote_control::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::remote_control::SetPositionResponse> should match
// service_traits::MD5Sum< ::remote_control::SetPosition >
template<>
struct MD5Sum< ::remote_control::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::SetPosition >::value();
  }
  static const char* value(const ::remote_control::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::SetPositionResponse> should match
// service_traits::DataType< ::remote_control::SetPosition >
template<>
struct DataType< ::remote_control::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::remote_control::SetPosition >::value();
  }
  static const char* value(const ::remote_control::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REMOTE_CONTROL_MESSAGE_SETPOSITION_H
