// Generated by gencpp from file remote_control/SetServo.msg
// DO NOT EDIT!


#ifndef REMOTE_CONTROL_MESSAGE_SETSERVO_H
#define REMOTE_CONTROL_MESSAGE_SETSERVO_H

#include <ros/service_traits.h>


#include <remote_control/SetServoRequest.h>
#include <remote_control/SetServoResponse.h>


namespace remote_control
{

struct SetServo
{

typedef SetServoRequest Request;
typedef SetServoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetServo
} // namespace remote_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::remote_control::SetServo > {
  static const char* value()
  {
    return "6e1eb645b22b8412b0f366c1854f41ef";
  }

  static const char* value(const ::remote_control::SetServo&) { return value(); }
};

template<>
struct DataType< ::remote_control::SetServo > {
  static const char* value()
  {
    return "remote_control/SetServo";
  }

  static const char* value(const ::remote_control::SetServo&) { return value(); }
};


// service_traits::MD5Sum< ::remote_control::SetServoRequest> should match
// service_traits::MD5Sum< ::remote_control::SetServo >
template<>
struct MD5Sum< ::remote_control::SetServoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::SetServo >::value();
  }
  static const char* value(const ::remote_control::SetServoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::SetServoRequest> should match
// service_traits::DataType< ::remote_control::SetServo >
template<>
struct DataType< ::remote_control::SetServoRequest>
{
  static const char* value()
  {
    return DataType< ::remote_control::SetServo >::value();
  }
  static const char* value(const ::remote_control::SetServoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::remote_control::SetServoResponse> should match
// service_traits::MD5Sum< ::remote_control::SetServo >
template<>
struct MD5Sum< ::remote_control::SetServoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::remote_control::SetServo >::value();
  }
  static const char* value(const ::remote_control::SetServoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::remote_control::SetServoResponse> should match
// service_traits::DataType< ::remote_control::SetServo >
template<>
struct DataType< ::remote_control::SetServoResponse>
{
  static const char* value()
  {
    return DataType< ::remote_control::SetServo >::value();
  }
  static const char* value(const ::remote_control::SetServoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REMOTE_CONTROL_MESSAGE_SETSERVO_H
