// Generated by gencpp from file opc_ros/ActionSetFileOp.msg
// DO NOT EDIT!


#ifndef OPC_ROS_MESSAGE_ACTIONSETFILEOP_H
#define OPC_ROS_MESSAGE_ACTIONSETFILEOP_H

#include <ros/service_traits.h>


#include <opc_ros/ActionSetFileOpRequest.h>
#include <opc_ros/ActionSetFileOpResponse.h>


namespace opc_ros
{

struct ActionSetFileOp
{

typedef ActionSetFileOpRequest Request;
typedef ActionSetFileOpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionSetFileOp
} // namespace opc_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::opc_ros::ActionSetFileOp > {
  static const char* value()
  {
    return "272e984a50155b54f97a32954cf22782";
  }

  static const char* value(const ::opc_ros::ActionSetFileOp&) { return value(); }
};

template<>
struct DataType< ::opc_ros::ActionSetFileOp > {
  static const char* value()
  {
    return "opc_ros/ActionSetFileOp";
  }

  static const char* value(const ::opc_ros::ActionSetFileOp&) { return value(); }
};


// service_traits::MD5Sum< ::opc_ros::ActionSetFileOpRequest> should match
// service_traits::MD5Sum< ::opc_ros::ActionSetFileOp >
template<>
struct MD5Sum< ::opc_ros::ActionSetFileOpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::opc_ros::ActionSetFileOp >::value();
  }
  static const char* value(const ::opc_ros::ActionSetFileOpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::opc_ros::ActionSetFileOpRequest> should match
// service_traits::DataType< ::opc_ros::ActionSetFileOp >
template<>
struct DataType< ::opc_ros::ActionSetFileOpRequest>
{
  static const char* value()
  {
    return DataType< ::opc_ros::ActionSetFileOp >::value();
  }
  static const char* value(const ::opc_ros::ActionSetFileOpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::opc_ros::ActionSetFileOpResponse> should match
// service_traits::MD5Sum< ::opc_ros::ActionSetFileOp >
template<>
struct MD5Sum< ::opc_ros::ActionSetFileOpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::opc_ros::ActionSetFileOp >::value();
  }
  static const char* value(const ::opc_ros::ActionSetFileOpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::opc_ros::ActionSetFileOpResponse> should match
// service_traits::DataType< ::opc_ros::ActionSetFileOp >
template<>
struct DataType< ::opc_ros::ActionSetFileOpResponse>
{
  static const char* value()
  {
    return DataType< ::opc_ros::ActionSetFileOp >::value();
  }
  static const char* value(const ::opc_ros::ActionSetFileOpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPC_ROS_MESSAGE_ACTIONSETFILEOP_H
