// Generated by gencpp from file opc_ros/ActionSetList.msg
// DO NOT EDIT!


#ifndef OPC_ROS_MESSAGE_ACTIONSETLIST_H
#define OPC_ROS_MESSAGE_ACTIONSETLIST_H

#include <ros/service_traits.h>


#include <opc_ros/ActionSetListRequest.h>
#include <opc_ros/ActionSetListResponse.h>


namespace opc_ros
{

struct ActionSetList
{

typedef ActionSetListRequest Request;
typedef ActionSetListResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ActionSetList
} // namespace opc_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::opc_ros::ActionSetList > {
  static const char* value()
  {
    return "eef2f65442e5649b9b3489933fa21e88";
  }

  static const char* value(const ::opc_ros::ActionSetList&) { return value(); }
};

template<>
struct DataType< ::opc_ros::ActionSetList > {
  static const char* value()
  {
    return "opc_ros/ActionSetList";
  }

  static const char* value(const ::opc_ros::ActionSetList&) { return value(); }
};


// service_traits::MD5Sum< ::opc_ros::ActionSetListRequest> should match
// service_traits::MD5Sum< ::opc_ros::ActionSetList >
template<>
struct MD5Sum< ::opc_ros::ActionSetListRequest>
{
  static const char* value()
  {
    return MD5Sum< ::opc_ros::ActionSetList >::value();
  }
  static const char* value(const ::opc_ros::ActionSetListRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::opc_ros::ActionSetListRequest> should match
// service_traits::DataType< ::opc_ros::ActionSetList >
template<>
struct DataType< ::opc_ros::ActionSetListRequest>
{
  static const char* value()
  {
    return DataType< ::opc_ros::ActionSetList >::value();
  }
  static const char* value(const ::opc_ros::ActionSetListRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::opc_ros::ActionSetListResponse> should match
// service_traits::MD5Sum< ::opc_ros::ActionSetList >
template<>
struct MD5Sum< ::opc_ros::ActionSetListResponse>
{
  static const char* value()
  {
    return MD5Sum< ::opc_ros::ActionSetList >::value();
  }
  static const char* value(const ::opc_ros::ActionSetListResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::opc_ros::ActionSetListResponse> should match
// service_traits::DataType< ::opc_ros::ActionSetList >
template<>
struct DataType< ::opc_ros::ActionSetListResponse>
{
  static const char* value()
  {
    return DataType< ::opc_ros::ActionSetList >::value();
  }
  static const char* value(const ::opc_ros::ActionSetListResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPC_ROS_MESSAGE_ACTIONSETLIST_H
