// Generated by gencpp from file opc_ros/SetJoint.msg
// DO NOT EDIT!


#ifndef OPC_ROS_MESSAGE_SETJOINT_H
#define OPC_ROS_MESSAGE_SETJOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opc_ros
{
template <class ContainerAllocator>
struct SetJoint_
{
  typedef SetJoint_<ContainerAllocator> Type;

  SetJoint_()
    : data(0.0)
    , duration(0.0)  {
    }
  SetJoint_(const ContainerAllocator& _alloc)
    : data(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef float _data_type;
  _data_type data;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::opc_ros::SetJoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opc_ros::SetJoint_<ContainerAllocator> const> ConstPtr;

}; // struct SetJoint_

typedef ::opc_ros::SetJoint_<std::allocator<void> > SetJoint;

typedef boost::shared_ptr< ::opc_ros::SetJoint > SetJointPtr;
typedef boost::shared_ptr< ::opc_ros::SetJoint const> SetJointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opc_ros::SetJoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opc_ros::SetJoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::opc_ros::SetJoint_<ContainerAllocator1> & lhs, const ::opc_ros::SetJoint_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::opc_ros::SetJoint_<ContainerAllocator1> & lhs, const ::opc_ros::SetJoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace opc_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::opc_ros::SetJoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opc_ros::SetJoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opc_ros::SetJoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opc_ros::SetJoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opc_ros::SetJoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opc_ros::SetJoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opc_ros::SetJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2a6e247129185fb38f8296bf00e1d24";
  }

  static const char* value(const ::opc_ros::SetJoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2a6e247129185fbULL;
  static const uint64_t static_value2 = 0x38f8296bf00e1d24ULL;
};

template<class ContainerAllocator>
struct DataType< ::opc_ros::SetJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opc_ros/SetJoint";
  }

  static const char* value(const ::opc_ros::SetJoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opc_ros::SetJoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 data\n"
"float32 duration\n"
;
  }

  static const char* value(const ::opc_ros::SetJoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opc_ros::SetJoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opc_ros::SetJoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opc_ros::SetJoint_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<float>::stream(s, indent + "  ", v.data);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPC_ROS_MESSAGE_SETJOINT_H
