// Generated by gencpp from file opc_ros/SetJetMax.msg
// DO NOT EDIT!


#ifndef OPC_ROS_MESSAGE_SETJETMAX_H
#define OPC_ROS_MESSAGE_SETJETMAX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opc_ros
{
template <class ContainerAllocator>
struct SetJetMax_
{
  typedef SetJetMax_<ContainerAllocator> Type;

  SetJetMax_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , duration(0.0)  {
    }
  SetJetMax_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , duration(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::opc_ros::SetJetMax_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opc_ros::SetJetMax_<ContainerAllocator> const> ConstPtr;

}; // struct SetJetMax_

typedef ::opc_ros::SetJetMax_<std::allocator<void> > SetJetMax;

typedef boost::shared_ptr< ::opc_ros::SetJetMax > SetJetMaxPtr;
typedef boost::shared_ptr< ::opc_ros::SetJetMax const> SetJetMaxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opc_ros::SetJetMax_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opc_ros::SetJetMax_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::opc_ros::SetJetMax_<ContainerAllocator1> & lhs, const ::opc_ros::SetJetMax_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::opc_ros::SetJetMax_<ContainerAllocator1> & lhs, const ::opc_ros::SetJetMax_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace opc_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::opc_ros::SetJetMax_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opc_ros::SetJetMax_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opc_ros::SetJetMax_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opc_ros::SetJetMax_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opc_ros::SetJetMax_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opc_ros::SetJetMax_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opc_ros::SetJetMax_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19cc8078d43cb0cd983e9688d658cb05";
  }

  static const char* value(const ::opc_ros::SetJetMax_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19cc8078d43cb0cdULL;
  static const uint64_t static_value2 = 0x983e9688d658cb05ULL;
};

template<class ContainerAllocator>
struct DataType< ::opc_ros::SetJetMax_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opc_ros/SetJetMax";
  }

  static const char* value(const ::opc_ros::SetJetMax_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opc_ros::SetJetMax_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 duration\n"
;
  }

  static const char* value(const ::opc_ros::SetJetMax_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opc_ros::SetJetMax_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetJetMax_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opc_ros::SetJetMax_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opc_ros::SetJetMax_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "duration: ";
    Printer<float>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPC_ROS_MESSAGE_SETJETMAX_H
