// Generated by gencpp from file opc_ros/SetTarget_object.msg
// DO NOT EDIT!


#ifndef OPC_ROS_MESSAGE_SETTARGET_OBJECT_H
#define OPC_ROS_MESSAGE_SETTARGET_OBJECT_H

#include <ros/service_traits.h>


#include <opc_ros/SetTarget_objectRequest.h>
#include <opc_ros/SetTarget_objectResponse.h>


namespace opc_ros
{

struct SetTarget_object
{

typedef SetTarget_objectRequest Request;
typedef SetTarget_objectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTarget_object
} // namespace opc_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::opc_ros::SetTarget_object > {
  static const char* value()
  {
    return "b043027b67620a7221fbfd7733360ab7";
  }

  static const char* value(const ::opc_ros::SetTarget_object&) { return value(); }
};

template<>
struct DataType< ::opc_ros::SetTarget_object > {
  static const char* value()
  {
    return "opc_ros/SetTarget_object";
  }

  static const char* value(const ::opc_ros::SetTarget_object&) { return value(); }
};


// service_traits::MD5Sum< ::opc_ros::SetTarget_objectRequest> should match
// service_traits::MD5Sum< ::opc_ros::SetTarget_object >
template<>
struct MD5Sum< ::opc_ros::SetTarget_objectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::opc_ros::SetTarget_object >::value();
  }
  static const char* value(const ::opc_ros::SetTarget_objectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::opc_ros::SetTarget_objectRequest> should match
// service_traits::DataType< ::opc_ros::SetTarget_object >
template<>
struct DataType< ::opc_ros::SetTarget_objectRequest>
{
  static const char* value()
  {
    return DataType< ::opc_ros::SetTarget_object >::value();
  }
  static const char* value(const ::opc_ros::SetTarget_objectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::opc_ros::SetTarget_objectResponse> should match
// service_traits::MD5Sum< ::opc_ros::SetTarget_object >
template<>
struct MD5Sum< ::opc_ros::SetTarget_objectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::opc_ros::SetTarget_object >::value();
  }
  static const char* value(const ::opc_ros::SetTarget_objectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::opc_ros::SetTarget_objectResponse> should match
// service_traits::DataType< ::opc_ros::SetTarget_object >
template<>
struct DataType< ::opc_ros::SetTarget_objectResponse>
{
  static const char* value()
  {
    return DataType< ::opc_ros::SetTarget_object >::value();
  }
  static const char* value(const ::opc_ros::SetTarget_objectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPC_ROS_MESSAGE_SETTARGET_OBJECT_H
