// Generated by gencpp from file opc_ros/SetTargetRequest.msg
// DO NOT EDIT!


#ifndef OPC_ROS_MESSAGE_SETTARGETREQUEST_H
#define OPC_ROS_MESSAGE_SETTARGETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opc_ros
{
template <class ContainerAllocator>
struct SetTargetRequest_
{
  typedef SetTargetRequest_<ContainerAllocator> Type;

  SetTargetRequest_()
    : color_name()
    , is_enable(false)  {
    }
  SetTargetRequest_(const ContainerAllocator& _alloc)
    : color_name(_alloc)
    , is_enable(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_name_type;
  _color_name_type color_name;

   typedef uint8_t _is_enable_type;
  _is_enable_type is_enable;





  typedef boost::shared_ptr< ::opc_ros::SetTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opc_ros::SetTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetRequest_

typedef ::opc_ros::SetTargetRequest_<std::allocator<void> > SetTargetRequest;

typedef boost::shared_ptr< ::opc_ros::SetTargetRequest > SetTargetRequestPtr;
typedef boost::shared_ptr< ::opc_ros::SetTargetRequest const> SetTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opc_ros::SetTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opc_ros::SetTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::opc_ros::SetTargetRequest_<ContainerAllocator1> & lhs, const ::opc_ros::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.color_name == rhs.color_name &&
    lhs.is_enable == rhs.is_enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::opc_ros::SetTargetRequest_<ContainerAllocator1> & lhs, const ::opc_ros::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace opc_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::opc_ros::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opc_ros::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opc_ros::SetTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opc_ros::SetTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opc_ros::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opc_ros::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opc_ros::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e558a1453be40987777ec3a3895b6b5b";
  }

  static const char* value(const ::opc_ros::SetTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe558a1453be40987ULL;
  static const uint64_t static_value2 = 0x777ec3a3895b6b5bULL;
};

template<class ContainerAllocator>
struct DataType< ::opc_ros::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opc_ros/SetTargetRequest";
  }

  static const char* value(const ::opc_ros::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opc_ros::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color_name\n"
"bool is_enable\n"
;
  }

  static const char* value(const ::opc_ros::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opc_ros::SetTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color_name);
      stream.next(m.is_enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opc_ros::SetTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opc_ros::SetTargetRequest_<ContainerAllocator>& v)
  {
    s << indent << "color_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color_name);
    s << indent << "is_enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPC_ROS_MESSAGE_SETTARGETREQUEST_H
