// Generated by gencpp from file opc_ros/SetTarget_objectRequest.msg
// DO NOT EDIT!


#ifndef OPC_ROS_MESSAGE_SETTARGET_OBJECTREQUEST_H
#define OPC_ROS_MESSAGE_SETTARGET_OBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opc_ros
{
template <class ContainerAllocator>
struct SetTarget_objectRequest_
{
  typedef SetTarget_objectRequest_<ContainerAllocator> Type;

  SetTarget_objectRequest_()
    : color_name()  {
    }
  SetTarget_objectRequest_(const ContainerAllocator& _alloc)
    : color_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_name_type;
  _color_name_type color_name;





  typedef boost::shared_ptr< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTarget_objectRequest_

typedef ::opc_ros::SetTarget_objectRequest_<std::allocator<void> > SetTarget_objectRequest;

typedef boost::shared_ptr< ::opc_ros::SetTarget_objectRequest > SetTarget_objectRequestPtr;
typedef boost::shared_ptr< ::opc_ros::SetTarget_objectRequest const> SetTarget_objectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::opc_ros::SetTarget_objectRequest_<ContainerAllocator1> & lhs, const ::opc_ros::SetTarget_objectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.color_name == rhs.color_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::opc_ros::SetTarget_objectRequest_<ContainerAllocator1> & lhs, const ::opc_ros::SetTarget_objectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace opc_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1ebd3bdb7f211ac2ddd328c08dba1e4";
  }

  static const char* value(const ::opc_ros::SetTarget_objectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1ebd3bdb7f211acULL;
  static const uint64_t static_value2 = 0x2ddd328c08dba1e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opc_ros/SetTarget_objectRequest";
  }

  static const char* value(const ::opc_ros::SetTarget_objectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color_name\n"
;
  }

  static const char* value(const ::opc_ros::SetTarget_objectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTarget_objectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opc_ros::SetTarget_objectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opc_ros::SetTarget_objectRequest_<ContainerAllocator>& v)
  {
    s << indent << "color_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPC_ROS_MESSAGE_SETTARGET_OBJECTREQUEST_H
