(cl:defpackage opc_ros-srv
  (:use )
  (:export
   "ACTIONSETFILEOP"
   "<ACTIONSETFILEOP-REQUEST>"
   "ACTIONSETFILEOP-REQUEST"
   "<ACTIONSETFILEOP-RESPONSE>"
   "ACTIONSETFILEOP-RESPONSE"
   "ACTIONSETLIST"
   "<ACTIONSETLIST-REQUEST>"
   "ACTIONSETLIST-REQUEST"
   "<ACTIONSETLIST-RESPONSE>"
   "ACTIONSETLIST-RESPONSE"
   "SETTARGET"
   "<SETTARGET-REQUEST>"
   "SETTARGET-REQUEST"
   "<SETTARGET-RESPONSE>"
   "SETTARGET-RESPONSE"
   "SETTARGET_OBJECT"
   "<SETTARGET_OBJECT-REQUEST>"
   "SETTARGET_OBJECT-REQUEST"
   "<SETTARGET_OBJECT-RESPONSE>"
   "SETTARGET_OBJECT-RESPONSE"
  ))

