// Generated by gencpp from file object_tracking/SetTargetRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_TRACKING_MESSAGE_SETTARGETREQUEST_H
#define OBJECT_TRACKING_MESSAGE_SETTARGETREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_tracking
{
template <class ContainerAllocator>
struct SetTargetRequest_
{
  typedef SetTargetRequest_<ContainerAllocator> Type;

  SetTargetRequest_()
    : color_name()  {
    }
  SetTargetRequest_(const ContainerAllocator& _alloc)
    : color_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_name_type;
  _color_name_type color_name;





  typedef boost::shared_ptr< ::object_tracking::SetTargetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_tracking::SetTargetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetTargetRequest_

typedef ::object_tracking::SetTargetRequest_<std::allocator<void> > SetTargetRequest;

typedef boost::shared_ptr< ::object_tracking::SetTargetRequest > SetTargetRequestPtr;
typedef boost::shared_ptr< ::object_tracking::SetTargetRequest const> SetTargetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_tracking::SetTargetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_tracking::SetTargetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_tracking::SetTargetRequest_<ContainerAllocator1> & lhs, const ::object_tracking::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return lhs.color_name == rhs.color_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_tracking::SetTargetRequest_<ContainerAllocator1> & lhs, const ::object_tracking::SetTargetRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_tracking

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_tracking::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_tracking::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracking::SetTargetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_tracking::SetTargetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracking::SetTargetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_tracking::SetTargetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_tracking::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1ebd3bdb7f211ac2ddd328c08dba1e4";
  }

  static const char* value(const ::object_tracking::SetTargetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1ebd3bdb7f211acULL;
  static const uint64_t static_value2 = 0x2ddd328c08dba1e4ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_tracking::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_tracking/SetTargetRequest";
  }

  static const char* value(const ::object_tracking::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_tracking::SetTargetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string color_name\n"
;
  }

  static const char* value(const ::object_tracking::SetTargetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_tracking::SetTargetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.color_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetTargetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_tracking::SetTargetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_tracking::SetTargetRequest_<ContainerAllocator>& v)
  {
    s << indent << "color_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_TRACKING_MESSAGE_SETTARGETREQUEST_H
